//! `R2Corpus`: anonymous, path-keyed corpus sync from a public HTTP(S)
//! bucket (Cloudflare R2 with public read, or anything that serves plain
//! GETs) — see imazen/codec-corpus#2.
//!
//! [`Corpus`](crate::Corpus) serves curated, versioned datasets from GitHub
//! release tarballs. `R2Corpus` targets *continuously-growing* corpora (fuzz
//! seeds, CI-generated fixtures) that are too large or too churny for
//! releases but still need an anonymous, cross-platform fetch.
//!
//! ## Storage layout
//!
//! For a prefix `fuzz/zentiff/fuzz_decode/` the bucket holds:
//!
//! ```text
//! <base>/fuzz/zentiff/fuzz_decode.list           auto-generated JSON index
//! <base>/fuzz/zentiff/fuzz_decode.tar.zst        optional frozen bundle
//! <base>/fuzz/zentiff/fuzz_decode/<rel-path>     individual objects
//! ```
//!
//! The `.list` is a [`ListIndex`]: `{ path: { size, sha256, in_bundle } }`
//! plus an optional [`BundleInfo`]. It is generated by a push tool
//! ([`ListIndex::from_dir`]), never hand-edited.
//!
//! ## Pull algorithm
//!
//! 1. Fetch the `.list` (one small request). If that fails but a previous
//!    pull left a cached list, the cached corpus is used as-is.
//! 2. Diff against the local cache by size + SHA-256.
//! 3. If a bundle exists and enough of its files are missing (default: 40 %),
//!    download it once and extract with the system `tar`.
//! 4. Fetch whatever is still missing as individual objects, several at a
//!    time ([`PullOptions::parallelism`]); every file is verified against its
//!    listed SHA-256 before it lands in place.
//! 5. Files in the cache dir that are no longer listed are removed, so the
//!    directory mirrors the remote prefix.
//! 6. If the `.list` names child prefixes ([`ListIndex::children`]), each
//!    child is pulled the same way into a sub-directory, so
//!    `pull("fuzz/zentiff/")` fetches every leaf under it and `pull("fuzz/")`
//!    fetches everything. The returned [`R2Corpus::list`] is the merged view
//!    (child files keyed `child/rel`).
//!
//! Downloads shell out to `curl`/`wget`/`powershell` like the rest of the
//! crate; nothing is compiled in. On `wasm32` only [`PullMode::Offline`] works
//! (it reads a cache populated on the host).

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::sync::atomic::{AtomicU64, Ordering};

use serde::{Deserialize, Serialize};

use crate::Error;
use crate::sha256;

/// Default public base URL for the imazen `codec-corpus` R2 bucket.
pub const DEFAULT_R2_BASE_URL: &str = "https://codec-corpus.r2.imazen.org";

/// Name of the cached copy of the remote `.list` inside a pulled prefix dir.
const CACHED_LIST_NAME: &str = ".list.json";

/// Current `.list` schema version.
pub const LIST_VERSION: u32 = 1;

// ---------------------------------------------------------------------------
// .list schema
// ---------------------------------------------------------------------------

/// One file in a [`ListIndex`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FileEntry {
    /// Size in bytes.
    pub size: u64,
    /// Lowercase hex SHA-256 of the contents.
    pub sha256: String,
    /// Whether the file is also contained in the prefix's bundle.
    #[serde(default)]
    pub in_bundle: bool,
}

/// The optional frozen `.tar` / `.tar.gz` / `.tar.zst` snapshot of a prefix.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BundleInfo {
    /// Object key relative to the base URL, e.g. `fuzz/zentiff/fuzz_decode.tar.zst`.
    pub key: String,
    /// Size of the archive in bytes.
    pub size: u64,
    /// Lowercase hex SHA-256 of the archive.
    pub sha256: String,
    /// Number of files inside the archive.
    pub file_count: u64,
    /// Sum of the member file sizes.
    pub uncompressed_size: u64,
}

/// The auto-generated `<prefix>.list` index of one corpus prefix.
///
/// Paths are relative to the prefix, forward-slash separated, and never
/// contain `..` or absolute components (pull rejects such lists).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ListIndex {
    /// Schema version ([`LIST_VERSION`]).
    pub version: u32,
    /// The prefix this index describes, with a trailing `/`.
    pub prefix: String,
    /// RFC 3339 timestamp of generation (informational).
    pub generated_at: String,
    /// The frozen bundle, if one has been published for this prefix.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bundle: Option<BundleInfo>,
    /// Every file under the prefix, keyed by relative path.
    pub files: BTreeMap<String, FileEntry>,
    /// Child prefixes (single path components, no `/`) that have their own
    /// `.list`. `pull` recurses into them; a push registers its leaf here.
    /// A node may have both `files` and `children`, but no file may live
    /// under a child's name.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub children: Vec<String>,
}

impl ListIndex {
    /// Parse a `.list` document.
    pub fn parse(json: &str) -> Result<Self, Error> {
        let list: ListIndex =
            serde_json::from_str(json).map_err(|e| Error::ListParse(e.to_string()))?;
        if list.version != LIST_VERSION {
            return Err(Error::ListParse(format!(
                "unsupported .list version {} (this crate speaks {LIST_VERSION})",
                list.version
            )));
        }
        list.validate()?;
        Ok(list)
    }

    /// Check every file path and child name for safety and mutual
    /// consistency (what [`ListIndex::parse`] enforces on input and a push
    /// enforces on output).
    pub fn validate(&self) -> Result<(), Error> {
        for path in self.files.keys() {
            validate_rel_path(path)?;
        }
        let mut seen = std::collections::BTreeSet::new();
        for child in &self.children {
            validate_rel_path(child)?;
            if child.contains('/') {
                return Err(Error::ListParse(format!(
                    "child prefix '{child}' must be a single path component"
                )));
            }
            if !seen.insert(child.as_str()) {
                return Err(Error::ListParse(format!(
                    "duplicate child prefix '{child}'"
                )));
            }
            let under = format!("{child}/");
            if self
                .files
                .keys()
                .any(|f| f == child || f.starts_with(&under))
            {
                return Err(Error::ListParse(format!(
                    "file entries collide with child prefix '{child}'"
                )));
            }
        }
        Ok(())
    }

    /// Register `child` as a sub-prefix of this node (idempotent, keeps the
    /// list sorted). Fails if the name is unsafe or collides with a file.
    pub fn add_child(&mut self, child: &str) -> Result<(), Error> {
        let child = child.trim_matches('/');
        if !self.children.iter().any(|c| c == child) {
            self.children.push(child.to_string());
            self.children.sort();
        }
        if let Err(e) = self.validate() {
            self.children.retain(|c| c != child);
            return Err(e);
        }
        Ok(())
    }

    /// Serialize to pretty JSON.
    pub fn to_json(&self) -> String {
        serde_json::to_string_pretty(self).expect("ListIndex is always serializable")
    }

    /// Build an index by walking `dir`: every regular file becomes an entry
    /// keyed by its `/`-separated path relative to `dir`, with size and
    /// SHA-256. No bundle is recorded (`in_bundle: false` everywhere).
    ///
    /// This is the push side's half of the format: upload the files under
    /// `prefix` and this document as `<prefix-without-trailing-slash>.list`.
    pub fn from_dir(dir: &Path, prefix: &str) -> Result<Self, Error> {
        let prefix = normalize_prefix(prefix)?;
        let mut files = BTreeMap::new();
        let mut stack = vec![dir.to_path_buf()];
        while let Some(d) = stack.pop() {
            let mut entries: Vec<_> = std::fs::read_dir(&d)?.collect::<Result<_, _>>()?;
            entries.sort_by_key(|e| e.file_name());
            for entry in entries {
                let path = entry.path();
                let name = entry.file_name();
                let name = name.to_string_lossy();
                if name.starts_with('.') {
                    continue; // .list.json, .lock, .tmp-*, editor droppings
                }
                if path.is_dir() {
                    stack.push(path);
                } else if path.is_file() {
                    let rel = path
                        .strip_prefix(dir)
                        .map_err(|e| std::io::Error::other(e.to_string()))?;
                    let rel = rel
                        .components()
                        .map(|c| c.as_os_str().to_string_lossy().into_owned())
                        .collect::<Vec<_>>()
                        .join("/");
                    let size = std::fs::metadata(&path)?.len();
                    let sha = sha256::sha256_file(&path)?;
                    files.insert(
                        rel,
                        FileEntry {
                            size,
                            sha256: sha,
                            in_bundle: false,
                        },
                    );
                }
            }
        }
        Ok(Self {
            version: LIST_VERSION,
            prefix,
            generated_at: rfc3339_now(),
            bundle: None,
            files,
            children: Vec::new(),
        })
    }

    /// An empty node list for `prefix` (no files, no bundle) — the shape a
    /// directory-only prefix such as `fuzz/` has before children are added.
    pub fn empty(prefix: &str) -> Result<Self, Error> {
        Ok(Self {
            version: LIST_VERSION,
            prefix: normalize_prefix(prefix)?,
            generated_at: rfc3339_now(),
            bundle: None,
            files: BTreeMap::new(),
            children: Vec::new(),
        })
    }

    /// Number of files listed.
    pub fn len(&self) -> usize {
        self.files.len()
    }

    /// Whether no files are listed.
    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }

    /// Sum of listed file sizes.
    pub fn total_size(&self) -> u64 {
        self.files.values().map(|f| f.size).sum()
    }
}

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

/// How a pull decides between the bundle and individual objects.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
#[non_exhaustive]
pub enum PullMode {
    /// Fetch the bundle when at least `bundle_threshold` of its files are
    /// missing locally, individual objects otherwise.
    #[default]
    Auto,
    /// Always fetch the bundle if the list has one (cold-start fast path).
    ForceBundle,
    /// Never fetch the bundle; individual objects only.
    NoBundle,
    /// Do no network I/O at all: open the cache left by a previous pull,
    /// verifying every listed file is present with the right SHA-256. Works
    /// on `wasm32`.
    Offline,
}

/// Tunables for [`R2Corpus::pull_with_options`]. Build with
/// [`PullOptions::default`] and the setters.
#[derive(Debug, Clone)]
pub struct PullOptions {
    mode: PullMode,
    cache_root: Option<PathBuf>,
    bundle_threshold: f32,
    prune: bool,
    parallelism: usize,
    recursive: bool,
}

/// Default number of concurrent individual-object fetches.
pub const DEFAULT_PARALLELISM: usize = 8;

impl Default for PullOptions {
    fn default() -> Self {
        Self {
            mode: PullMode::Auto,
            cache_root: None,
            bundle_threshold: 0.4,
            prune: true,
            parallelism: DEFAULT_PARALLELISM,
            recursive: true,
        }
    }
}

impl PullOptions {
    /// Bundle-vs-individual policy (default [`PullMode::Auto`]).
    pub fn mode(mut self, mode: PullMode) -> Self {
        self.mode = mode;
        self
    }

    /// Explicit cache root (default: `CODEC_CORPUS_CACHE` env var, else the
    /// platform cache dir). Files land under `{root}/codec-corpus/r2/…`.
    pub fn cache_root(mut self, root: impl Into<PathBuf>) -> Self {
        self.cache_root = Some(root.into());
        self
    }

    /// In [`PullMode::Auto`], the fraction (`0.0..=1.0`) of bundled files that
    /// must be missing before the bundle is fetched instead of individual
    /// objects. Default `0.4`.
    pub fn bundle_threshold(mut self, fraction: f32) -> Self {
        self.bundle_threshold = fraction.clamp(0.0, 1.0);
        self
    }

    /// Whether to delete cached files that are no longer in the `.list`
    /// (default `true`, so the directory mirrors the remote prefix).
    pub fn prune(mut self, prune: bool) -> Self {
        self.prune = prune;
        self
    }

    /// How many individual objects to fetch concurrently (default
    /// [`DEFAULT_PARALLELISM`]; `0` and `1` both mean sequential). Each fetch
    /// is its own `curl`/`wget` process, so this is also the number of
    /// concurrent connections.
    pub fn parallelism(mut self, n: usize) -> Self {
        self.parallelism = n.max(1);
        self
    }

    /// Whether to pull child prefixes named in the `.list` (default `true`).
    /// With `false` only the node's own files are synced.
    pub fn recursive(mut self, recursive: bool) -> Self {
        self.recursive = recursive;
        self
    }
}

// ---------------------------------------------------------------------------
// R2Corpus
// ---------------------------------------------------------------------------

/// A pulled corpus prefix: a local directory that mirrors
/// `<base_url>/<prefix>` and can be walked with `std::fs`.
///
/// ```no_run
/// let corpus = codec_corpus::R2Corpus::pull(
///     codec_corpus::DEFAULT_R2_BASE_URL,
///     "fuzz/zentiff/fuzz_decode/",
/// )?;
/// for entry in std::fs::read_dir(corpus.path())? {
///     let bytes = std::fs::read(entry?.path())?;
///     // feed your decoder...
/// }
/// # Ok::<(), Box<dyn std::error::Error>>(())
/// ```
#[derive(Debug)]
pub struct R2Corpus {
    base_url: String,
    prefix: String,
    dir: PathBuf,
    list: ListIndex,
}

/// Something that fetches `url` into the file at `dest`. The real one is the
/// crate's `curl`/`wget`/`powershell` chain; tests inject a local copier. It
/// is called from several threads at once when fetching individual objects.
pub(crate) type Fetcher<'a> = &'a (dyn Fn(&str, &Path) -> Result<(), Error> + Sync);

impl R2Corpus {
    /// Pull `prefix` from `base_url` (anonymous HTTP GETs) into the cache and
    /// return a handle to the local directory. See the module docs for the
    /// algorithm.
    pub fn pull(base_url: &str, prefix: &str) -> Result<Self, Error> {
        Self::pull_with_options(base_url, prefix, PullOptions::default())
    }

    /// [`R2Corpus::pull`] with explicit [`PullOptions`].
    pub fn pull_with_options(
        base_url: &str,
        prefix: &str,
        options: PullOptions,
    ) -> Result<Self, Error> {
        #[cfg(target_arch = "wasm32")]
        {
            if options.mode != PullMode::Offline {
                return Err(Error::DownloadUnsupported {
                    dataset: prefix.to_string(),
                });
            }
            Self::pull_with_fetcher(base_url, prefix, options, &|_url, _dest| {
                Err(Error::DownloadUnsupported {
                    dataset: prefix.to_string(),
                })
            })
        }
        #[cfg(not(target_arch = "wasm32"))]
        {
            Self::pull_with_fetcher(base_url, prefix, options, &crate::download::download_file)
        }
    }

    /// Local directory mirroring the remote prefix.
    pub fn path(&self) -> &Path {
        &self.dir
    }

    /// The `.list` this directory was synced against. When the prefix has
    /// child prefixes (and the pull was recursive) this is the merged view:
    /// the node's own files plus every child's files keyed `child/rel`, with
    /// the node's own `bundle` and `children`.
    pub fn list(&self) -> &ListIndex {
        &self.list
    }

    /// The normalized prefix (trailing `/`).
    pub fn prefix(&self) -> &str {
        &self.prefix
    }

    /// The base URL this corpus was pulled from.
    pub fn base_url(&self) -> &str {
        &self.base_url
    }

    /// Local path of one listed file (whether or not it exists yet).
    pub fn file_path(&self, rel: &str) -> PathBuf {
        join_rel(&self.dir, rel)
    }

    /// Iterate `(relative path, entry)` in stable (sorted) order.
    pub fn files(&self) -> impl Iterator<Item = (&str, &FileEntry)> {
        self.list.files.iter().map(|(k, v)| (k.as_str(), v))
    }

    pub(crate) fn pull_with_fetcher(
        base_url: &str,
        prefix: &str,
        options: PullOptions,
        fetch: Fetcher<'_>,
    ) -> Result<Self, Error> {
        let base_url = base_url.trim_end_matches('/').to_string();
        let prefix = normalize_prefix(prefix)?;
        let cache_base = match &options.cache_root {
            Some(r) => r.clone(),
            None => default_cache_base()?,
        };
        let dir = cache_dir_for(&cache_base, &base_url, &prefix);
        std::fs::create_dir_all(&dir)?;

        let list = with_dir_lock(&dir, || {
            sync_prefix(&base_url, &prefix, &dir, &options, fetch)
        })?;

        Ok(Self {
            base_url,
            prefix,
            dir,
            list,
        })
    }
}

/// The locked body of a pull: returns the list the directory now matches.
fn sync_prefix(
    base_url: &str,
    prefix: &str,
    dir: &Path,
    options: &PullOptions,
    fetch: Fetcher<'_>,
) -> Result<ListIndex, Error> {
    let cached_list_path = dir.join(CACHED_LIST_NAME);

    // 1. The list.
    let mut list = if options.mode == PullMode::Offline {
        let text =
            std::fs::read_to_string(&cached_list_path).map_err(|_| Error::NetworkUnavailable {
                dataset: prefix.to_string(),
            })?;
        ListIndex::parse(&text)?
    } else {
        let tmp = temp_path(dir, "list");
        match fetch(&list_url(base_url, prefix), &tmp) {
            Ok(()) => {
                let text = std::fs::read_to_string(&tmp)?;
                let _ = std::fs::remove_file(&tmp);
                ListIndex::parse(&text)?
            }
            Err(_) => {
                let _ = std::fs::remove_file(&tmp);
                // Fall back to the last successful pull, if any.
                let Ok(text) = std::fs::read_to_string(&cached_list_path) else {
                    return Err(Error::NetworkUnavailable {
                        dataset: prefix.to_string(),
                    });
                };
                eprintln!(
                    "codec-corpus: warning: could not fetch {}; using the cached list for '{prefix}'",
                    list_url(base_url, prefix)
                );
                ListIndex::parse(&text)?
            }
        }
    };

    // 2. Diff.
    let mut missing: Vec<&str> = Vec::new();
    for (rel, entry) in &list.files {
        if !local_matches(&join_rel(dir, rel), entry) {
            missing.push(rel);
        }
    }

    if options.mode == PullMode::Offline {
        if let Some(first) = missing.first() {
            return Err(Error::PathNotFound {
                path: format!("{prefix}{first} (offline; {} files missing)", missing.len()),
            });
        }
        if options.recursive {
            sync_children(base_url, prefix, dir, &mut list, options, fetch)?;
        }
        return Ok(list);
    }

    // 3. Bundle.
    if let Some(bundle) = &list.bundle {
        let missing_bundled = missing
            .iter()
            .filter(|rel| list.files[**rel].in_bundle)
            .count();
        let use_bundle = match options.mode {
            PullMode::ForceBundle => true,
            PullMode::NoBundle | PullMode::Offline => false,
            PullMode::Auto => {
                missing_bundled > 0
                    && (missing_bundled as f32 / bundle.file_count.max(1) as f32)
                        >= options.bundle_threshold
            }
        };
        if use_bundle {
            fetch_bundle(base_url, dir, &list, bundle, fetch)?;
            missing.retain(|rel| !local_matches(&join_rel(dir, rel), &list.files[*rel]));
        }
    }

    // 4. Individual objects.
    fetch_objects(
        base_url,
        prefix,
        dir,
        &list,
        &missing,
        options.parallelism,
        fetch,
    )?;

    // 5. Prune + record the list we now match.
    if options.prune {
        prune_unlisted(dir, dir, &list)?;
    }
    let tmp = temp_path(dir, "list");
    std::fs::write(&tmp, list.to_json())?;
    std::fs::rename(&tmp, &cached_list_path)?;

    // 6. Children.
    if options.recursive {
        sync_children(base_url, prefix, dir, &mut list, options, fetch)?;
    }
    Ok(list)
}

/// Pull every child prefix named in `list` into `dir/<child>/` and fold its
/// files into `list` as `child/rel` (the merged view).
fn sync_children(
    base_url: &str,
    prefix: &str,
    dir: &Path,
    list: &mut ListIndex,
    options: &PullOptions,
    fetch: Fetcher<'_>,
) -> Result<(), Error> {
    let children = list.children.clone();
    for child in &children {
        let child_prefix = format!("{prefix}{child}/");
        let child_dir = dir.join(child);
        std::fs::create_dir_all(&child_dir)?;
        let child_list = with_dir_lock(&child_dir, || {
            sync_prefix(base_url, &child_prefix, &child_dir, options, fetch)
        })?;
        for (rel, entry) in child_list.files {
            list.files.insert(format!("{child}/{rel}"), entry);
        }
    }
    Ok(())
}

/// Fetch `missing` objects into place, `parallelism` at a time. The first
/// failure stops the remaining work and is returned; files already placed
/// stay (they were verified), temp files are cleaned up.
fn fetch_objects(
    base_url: &str,
    prefix: &str,
    dir: &Path,
    list: &ListIndex,
    missing: &[&str],
    parallelism: usize,
    fetch: Fetcher<'_>,
) -> Result<(), Error> {
    if missing.is_empty() {
        return Ok(());
    }
    let fetch_one = |rel: &str| -> Result<(), Error> {
        let entry = &list.files[rel];
        let dest = join_rel(dir, rel);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let tmp = temp_path(dir, "obj");
        let url = file_url(base_url, prefix, rel);
        if let Err(e) = fetch(&url, &tmp) {
            let _ = std::fs::remove_file(&tmp);
            return Err(match e {
                Error::Io(io) => Error::Io(io),
                _ => Error::DownloadFailed {
                    url,
                    reason: "all download methods failed (curl, wget, powershell)".to_string(),
                },
            });
        }
        place_verified(&tmp, &dest, rel, entry)
    };

    // wasm32 has no threads to spawn; a single worker is also the
    // deterministic path tests use to pin error ordering.
    let workers = if cfg!(target_arch = "wasm32") {
        1
    } else {
        parallelism.clamp(1, missing.len())
    };
    if workers == 1 {
        for rel in missing {
            fetch_one(rel)?;
        }
        return Ok(());
    }

    let next = Mutex::new(0usize);
    let failure: Mutex<Option<Error>> = Mutex::new(None);
    std::thread::scope(|scope| {
        for _ in 0..workers {
            scope.spawn(|| {
                loop {
                    let i = {
                        let mut n = next.lock().unwrap_or_else(|p| p.into_inner());
                        let i = *n;
                        *n += 1;
                        i
                    };
                    if i >= missing.len() {
                        return;
                    }
                    if failure.lock().unwrap_or_else(|p| p.into_inner()).is_some() {
                        return;
                    }
                    if let Err(e) = fetch_one(missing[i]) {
                        let mut f = failure.lock().unwrap_or_else(|p| p.into_inner());
                        if f.is_none() {
                            *f = Some(e);
                        }
                        return;
                    }
                }
            });
        }
    });
    match failure.into_inner().unwrap_or_else(|p| p.into_inner()) {
        Some(e) => Err(e),
        None => Ok(()),
    }
}

/// Download, verify, and extract the bundle, moving every listed
/// `in_bundle` member whose hash checks out into place.
fn fetch_bundle(
    base_url: &str,
    dir: &Path,
    list: &ListIndex,
    bundle: &BundleInfo,
    fetch: Fetcher<'_>,
) -> Result<(), Error> {
    let url = bundle_url(base_url, &bundle.key);
    let archive = temp_path(dir, "bundle");
    if let Err(e) = fetch(&url, &archive) {
        let _ = std::fs::remove_file(&archive);
        return Err(match e {
            Error::Io(io) => Error::Io(io),
            _ => Error::DownloadFailed {
                url,
                reason: "all download methods failed (curl, wget, powershell)".to_string(),
            },
        });
    }
    let actual = sha256::sha256_file(&archive)?;
    if actual != bundle.sha256 {
        let _ = std::fs::remove_file(&archive);
        return Err(Error::ChecksumMismatch {
            path: bundle.key.clone(),
            expected: bundle.sha256.clone(),
            actual,
        });
    }

    let extract = temp_path(dir, "extract");
    std::fs::create_dir_all(&extract)?;
    let extracted = extract_archive(&archive, &bundle.key, &extract);
    let _ = std::fs::remove_file(&archive);
    if let Err(e) = extracted {
        let _ = std::fs::remove_dir_all(&extract);
        return Err(e);
    }

    for (rel, entry) in &list.files {
        if !entry.in_bundle {
            continue;
        }
        let src = join_rel(&extract, rel);
        if !src.is_file() {
            continue; // stale list vs bundle: the delta path picks it up
        }
        let dest = join_rel(dir, rel);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // A member whose hash disagrees with the list is simply not placed;
        // it is re-fetched individually (and verified) afterwards.
        if sha256::sha256_file(&src)? == entry.sha256 {
            move_file(&src, &dest)?;
        }
    }
    let _ = std::fs::remove_dir_all(&extract);
    Ok(())
}

/// Extract `archive` (format chosen by the extension of `key`) into `dest`
/// with the system `tar`, falling back to a standalone `zstd` for `.tar.zst`
/// when `tar` lacks built-in zstd support.
fn extract_archive(archive: &Path, key: &str, dest: &Path) -> Result<(), Error> {
    use std::process::{Command, Stdio};
    let run_tar = |args: &[&str], input: &Path| -> bool {
        Command::new("tar")
            .args(args)
            .arg(input)
            .arg("-C")
            .arg(dest)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    };
    let ok = if key.ends_with(".tar.zst") || key.ends_with(".tzst") {
        run_tar(&["--zstd", "-xf"], archive) || {
            // Decompress to a sibling .tar with the zstd binary, then plain tar.
            let plain = archive.with_extension("tar");
            let decompressed = Command::new("zstd")
                .args(["-d", "-q", "-f", "-o"])
                .arg(&plain)
                .arg(archive)
                .stdout(Stdio::null())
                .stderr(Stdio::null())
                .status()
                .map(|s| s.success())
                .unwrap_or(false);
            let r = decompressed && run_tar(&["-xf"], &plain);
            let _ = std::fs::remove_file(&plain);
            r
        }
    } else if key.ends_with(".tar.gz") || key.ends_with(".tgz") {
        run_tar(&["-xzf"], archive)
    } else if key.ends_with(".tar") {
        run_tar(&["-xf"], archive)
    } else {
        return Err(Error::ListParse(format!(
            "bundle key '{key}' has an unsupported archive extension (want .tar, .tar.gz, .tar.zst)"
        )));
    };
    if ok {
        Ok(())
    } else {
        Err(Error::DownloadFailed {
            url: key.to_string(),
            reason: "bundle extraction failed (is `tar` — and `zstd` for .tar.zst — installed?)"
                .to_string(),
        })
    }
}

/// Verify `tmp` against `entry`, then move it to `dest`. On mismatch the
/// temp file is deleted and nothing is placed.
fn place_verified(tmp: &Path, dest: &Path, rel: &str, entry: &FileEntry) -> Result<(), Error> {
    let size = std::fs::metadata(tmp)?.len();
    let actual = sha256::sha256_file(tmp)?;
    if size != entry.size || actual != entry.sha256 {
        let _ = std::fs::remove_file(tmp);
        return Err(Error::ChecksumMismatch {
            path: rel.to_string(),
            expected: entry.sha256.clone(),
            actual,
        });
    }
    move_file(tmp, dest)
}

fn move_file(src: &Path, dest: &Path) -> Result<(), Error> {
    if std::fs::rename(src, dest).is_err() {
        std::fs::copy(src, dest)?;
        let _ = std::fs::remove_file(src);
    }
    Ok(())
}

/// Does the local file exist with the listed size and SHA-256?
fn local_matches(path: &Path, entry: &FileEntry) -> bool {
    let Ok(meta) = std::fs::metadata(path) else {
        return false;
    };
    if !meta.is_file() || meta.len() != entry.size {
        return false;
    }
    matches!(sha256::sha256_file(path), Ok(h) if h == entry.sha256)
}

/// Remove regular files under `dir` that are not listed (hidden names at the
/// root — `.list.json`, `.lock`, `.tmp-*` — are the crate's own and stay).
/// Child-prefix directories are owned by their own sync and are skipped.
fn prune_unlisted(root: &Path, dir: &Path, list: &ListIndex) -> Result<(), Error> {
    for entry in std::fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let name = entry.file_name();
        if dir == root && name.to_string_lossy().starts_with('.') {
            continue;
        }
        if dir == root && path.is_dir() && list.children.iter().any(|c| **c == *name) {
            continue;
        }
        if path.is_dir() {
            prune_unlisted(root, &path, list)?;
            // Drop directories that ended up empty.
            if std::fs::read_dir(&path)?.next().is_none() {
                let _ = std::fs::remove_dir(&path);
            }
        } else {
            let rel = path
                .strip_prefix(root)
                .map_err(|e| std::io::Error::other(e.to_string()))?
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            if !list.files.contains_key(&rel) {
                std::fs::remove_file(&path)?;
            }
        }
    }
    Ok(())
}

// ---------------------------------------------------------------------------
// Layout helpers (pure)
// ---------------------------------------------------------------------------

/// Strip leading `/`, require a non-empty, `..`-free path, add a trailing `/`.
pub(crate) fn normalize_prefix(prefix: &str) -> Result<String, Error> {
    let trimmed = prefix.trim_matches('/');
    if trimmed.is_empty() {
        return Err(Error::ListParse("prefix must not be empty".to_string()));
    }
    validate_rel_path(trimmed)?;
    Ok(format!("{trimmed}/"))
}

/// Reject absolute paths, `..`, empty components, and backslashes.
fn validate_rel_path(rel: &str) -> Result<(), Error> {
    let bad = rel.is_empty()
        || rel.starts_with('/')
        || rel.contains('\\')
        || rel.contains('\0')
        || rel
            .split('/')
            .any(|c| c.is_empty() || c == "." || c == "..");
    if bad {
        Err(Error::ListParse(format!("unsafe path in .list: '{rel}'")))
    } else {
        Ok(())
    }
}

/// `<base>/<prefix-without-trailing-slash>.list`
pub(crate) fn list_url(base_url: &str, prefix: &str) -> String {
    format!(
        "{}/{}.list",
        base_url.trim_end_matches('/'),
        prefix.trim_end_matches('/')
    )
}

/// `<base>/<prefix><rel>`
pub(crate) fn file_url(base_url: &str, prefix: &str, rel: &str) -> String {
    format!("{}/{prefix}{rel}", base_url.trim_end_matches('/'))
}

/// `<base>/<key>`
pub(crate) fn bundle_url(base_url: &str, key: &str) -> String {
    format!(
        "{}/{}",
        base_url.trim_end_matches('/'),
        key.trim_start_matches('/')
    )
}

/// `{cache_base}/codec-corpus/r2/{host}/{prefix components...}`
pub(crate) fn cache_dir_for(cache_base: &Path, base_url: &str, prefix: &str) -> PathBuf {
    let host = base_url
        .split("://")
        .nth(1)
        .unwrap_or(base_url)
        .trim_end_matches('/');
    let host: String = host
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '.' {
                c
            } else {
                '_'
            }
        })
        .collect();
    let mut dir = cache_base.join("codec-corpus").join("r2").join(host);
    for comp in prefix.trim_end_matches('/').split('/') {
        dir.push(comp);
    }
    dir
}

fn join_rel(dir: &Path, rel: &str) -> PathBuf {
    let mut p = dir.to_path_buf();
    for comp in rel.split('/') {
        p.push(comp);
    }
    p
}

fn default_cache_base() -> Result<PathBuf, Error> {
    if let Ok(val) = std::env::var("CODEC_CORPUS_CACHE") {
        return Ok(PathBuf::from(val));
    }
    dirs::cache_dir().ok_or(Error::NoCacheDir)
}

fn temp_path(dir: &Path, tag: &str) -> PathBuf {
    // pid + a process-wide counter: unique across concurrent worker threads
    // (a timestamp alone can collide within the clock's resolution).
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let pid = std::process::id();
    let n = COUNTER.fetch_add(1, Ordering::Relaxed);
    dir.join(format!(".tmp-{tag}-{pid}-{n}"))
}

/// Coarse RFC 3339 UTC timestamp without a date library (days since epoch
/// → civil date via the standard algorithm).
fn rfc3339_now() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    let days = (secs / 86_400) as i64;
    let rem = secs % 86_400;
    let (h, m, s) = (rem / 3600, (rem % 3600) / 60, rem % 60);
    // Howard Hinnant's civil_from_days.
    let z = days + 719_468;
    let era = z.div_euclid(146_097);
    let doe = z.rem_euclid(146_097);
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if mo <= 2 { y + 1 } else { y };
    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{m:02}:{s:02}Z")
}

/// Hold the prefix dir's `.lock` for the duration of `f` (native only).
fn with_dir_lock<T>(dir: &Path, f: impl FnOnce() -> Result<T, Error>) -> Result<T, Error> {
    #[cfg(not(target_arch = "wasm32"))]
    {
        let lock_file = std::fs::File::create(dir.join(".lock"))?;
        let mut lock = fd_lock::RwLock::new(lock_file);
        let _guard = lock.write()?;
        f()
    }
    #[cfg(target_arch = "wasm32")]
    {
        // Single-process runtime: nothing to lock against.
        let _ = dir;
        f()
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn url_layout() {
        assert_eq!(
            list_url("https://x.example/", "fuzz/zentiff/fuzz_decode/"),
            "https://x.example/fuzz/zentiff/fuzz_decode.list"
        );
        assert_eq!(
            file_url("https://x.example", "fuzz/zentiff/fuzz_decode/", "sub/abc"),
            "https://x.example/fuzz/zentiff/fuzz_decode/sub/abc"
        );
        assert_eq!(
            bundle_url("https://x.example", "fuzz/zentiff/fuzz_decode.tar.zst"),
            "https://x.example/fuzz/zentiff/fuzz_decode.tar.zst"
        );
    }

    #[test]
    fn prefix_normalization_and_safety() {
        assert_eq!(normalize_prefix("fuzz/zentiff").unwrap(), "fuzz/zentiff/");
        assert_eq!(normalize_prefix("/fuzz/zentiff/").unwrap(), "fuzz/zentiff/");
        assert!(normalize_prefix("").is_err());
        assert!(normalize_prefix("/").is_err());
        assert!(normalize_prefix("a/../b").is_err());
        assert!(normalize_prefix("a//b").is_err());
        assert!(validate_rel_path("ok/path.bin").is_ok());
        assert!(validate_rel_path("../escape").is_err());
        assert!(validate_rel_path("/abs").is_err());
        assert!(validate_rel_path("win\\path").is_err());
    }

    #[test]
    fn cache_dir_layout() {
        let d = cache_dir_for(
            Path::new("/cache"),
            "https://codec-corpus.r2.imazen.org",
            "fuzz/zentiff/fuzz_decode/",
        );
        assert_eq!(
            d,
            Path::new("/cache/codec-corpus/r2/codec-corpus.r2.imazen.org/fuzz/zentiff/fuzz_decode")
        );
    }

    #[test]
    fn list_parse_rejects_bad_version_and_unsafe_paths() {
        let bad_version = r#"{"version":2,"prefix":"p/","generated_at":"","files":{}}"#;
        assert!(matches!(
            ListIndex::parse(bad_version),
            Err(Error::ListParse(_))
        ));
        let escape = r#"{"version":1,"prefix":"p/","generated_at":"","files":{"../x":{"size":1,"sha256":"a"}}}"#;
        assert!(matches!(ListIndex::parse(escape), Err(Error::ListParse(_))));
        let ok = r#"{"version":1,"prefix":"p/","generated_at":"","files":{"x":{"size":1,"sha256":"a"}}}"#;
        let list = ListIndex::parse(ok).unwrap();
        assert!(!list.files["x"].in_bundle, "in_bundle defaults to false");
        assert!(list.bundle.is_none());
    }

    #[test]
    fn rfc3339_now_is_well_formed() {
        let s = rfc3339_now();
        assert_eq!(s.len(), 20, "{s}");
        assert!(s.starts_with("20"), "{s}");
        assert!(s.ends_with('Z'));
    }

    // Filesystem-backed tests: a fake "remote" directory stands in for the
    // bucket and a copying fetcher stands in for curl.
    #[cfg(not(target_arch = "wasm32"))]
    mod sync {
        use super::*;

        const BASE: &str = "https://fake.example";
        const PREFIX: &str = "fuzz/demo/seeds/";

        struct Fixture {
            root: PathBuf,
            remote: PathBuf,
            cache: PathBuf,
            fetched: Mutex<Vec<String>>,
        }

        impl Fixture {
            fn new(name: &str) -> Self {
                let root = std::env::temp_dir().join(format!("codec-corpus-r2-test-{name}"));
                let _ = std::fs::remove_dir_all(&root);
                let remote = root.join("remote");
                let cache = root.join("cache");
                std::fs::create_dir_all(&remote).unwrap();
                std::fs::create_dir_all(&cache).unwrap();
                Self {
                    root,
                    remote,
                    cache,
                    fetched: Mutex::new(Vec::new()),
                }
            }

            /// Map a URL under BASE to a file in the fake remote and copy it.
            fn fetcher(&self) -> impl Fn(&str, &Path) -> Result<(), Error> + Sync + '_ {
                move |url: &str, dest: &Path| {
                    self.fetched.lock().unwrap().push(url.to_string());
                    let rel = url
                        .strip_prefix(&format!("{BASE}/"))
                        .expect("url under BASE");
                    let src = join_rel(&self.remote, rel);
                    if !src.is_file() {
                        return Err(Error::NetworkUnavailable {
                            dataset: rel.to_string(),
                        });
                    }
                    std::fs::copy(&src, dest)?;
                    Ok(())
                }
            }

            fn fetched_count(&self, suffix: &str) -> usize {
                self.fetched
                    .lock()
                    .unwrap()
                    .iter()
                    .filter(|u| u.ends_with(suffix))
                    .count()
            }

            fn fetched_total(&self) -> usize {
                self.fetched.lock().unwrap().len()
            }

            fn reset_log(&self) {
                self.fetched.lock().unwrap().clear();
            }

            fn put_object(&self, rel: &str, bytes: &[u8]) {
                self.put_raw(&format!("{PREFIX}{rel}"), bytes);
            }

            /// Write an object at an arbitrary key under the fake remote.
            fn put_raw(&self, key: &str, bytes: &[u8]) {
                let p = join_rel(&self.remote, key);
                std::fs::create_dir_all(p.parent().unwrap()).unwrap();
                std::fs::write(p, bytes).unwrap();
            }

            fn put_list(&self, list: &ListIndex) {
                self.put_list_at(PREFIX, list);
            }

            /// Serve `list` as the `.list` of an arbitrary prefix.
            fn put_list_at(&self, prefix: &str, list: &ListIndex) {
                let p = join_rel(
                    &self.remote,
                    &format!("{}.list", prefix.trim_end_matches('/')),
                );
                std::fs::create_dir_all(p.parent().unwrap()).unwrap();
                std::fs::write(p, list.to_json()).unwrap();
            }

            fn options(&self) -> PullOptions {
                PullOptions::default().cache_root(&self.cache)
            }

            fn pull(&self, options: PullOptions) -> Result<R2Corpus, Error> {
                self.pull_prefix(PREFIX, options)
            }

            fn pull_prefix(&self, prefix: &str, options: PullOptions) -> Result<R2Corpus, Error> {
                let f = self.fetcher();
                R2Corpus::pull_with_fetcher(BASE, prefix, options, &f)
            }

            fn cleanup(self) {
                let _ = std::fs::remove_dir_all(&self.root);
            }
        }

        fn entry(bytes: &[u8], in_bundle: bool) -> FileEntry {
            FileEntry {
                size: bytes.len() as u64,
                sha256: sha256::sha256_hex(bytes),
                in_bundle,
            }
        }

        fn list_with(files: &[(&str, &[u8], bool)], bundle: Option<BundleInfo>) -> ListIndex {
            list_for(PREFIX, files, bundle)
        }

        fn list_for(
            prefix: &str,
            files: &[(&str, &[u8], bool)],
            bundle: Option<BundleInfo>,
        ) -> ListIndex {
            ListIndex {
                version: LIST_VERSION,
                prefix: prefix.to_string(),
                generated_at: "2026-01-01T00:00:00Z".to_string(),
                bundle,
                files: files
                    .iter()
                    .map(|(p, b, ib)| (p.to_string(), entry(b, *ib)))
                    .collect(),
                children: Vec::new(),
            }
        }

        /// A minimal ustar writer so bundle tests need no `tar -c`.
        fn ustar(members: &[(&str, &[u8])]) -> Vec<u8> {
            let mut out = Vec::new();
            for (name, data) in members {
                let mut h = [0u8; 512];
                h[..name.len()].copy_from_slice(name.as_bytes());
                h[100..108].copy_from_slice(b"0000644\0");
                h[108..116].copy_from_slice(b"0000000\0");
                h[116..124].copy_from_slice(b"0000000\0");
                h[124..136].copy_from_slice(format!("{:011o}\0", data.len()).as_bytes());
                h[136..148].copy_from_slice(b"00000000000\0");
                h[148..156].copy_from_slice(b"        ");
                h[156] = b'0';
                h[257..263].copy_from_slice(b"ustar\0");
                h[263..265].copy_from_slice(b"00");
                let sum: u32 = h.iter().map(|&b| b as u32).sum();
                h[148..156].copy_from_slice(format!("{sum:06o}\0 ").as_bytes());
                out.extend_from_slice(&h);
                out.extend_from_slice(data);
                let pad = (512 - data.len() % 512) % 512;
                out.extend(std::iter::repeat_n(0u8, pad));
            }
            out.extend(std::iter::repeat_n(0u8, 1024));
            out
        }

        #[test]
        fn pull_fetches_and_verifies_individual_files_then_is_a_noop() {
            let fx = Fixture::new("individual");
            let a = b"alpha seed".as_slice();
            let b = b"beta seed, longer".as_slice();
            fx.put_object("a.bin", a);
            fx.put_object("sub/b.bin", b);
            fx.put_list(&list_with(
                &[("a.bin", a, false), ("sub/b.bin", b, false)],
                None,
            ));

            let corpus = fx.pull(fx.options()).unwrap();
            assert_eq!(corpus.prefix(), PREFIX);
            assert_eq!(std::fs::read(corpus.file_path("a.bin")).unwrap(), a);
            assert_eq!(std::fs::read(corpus.file_path("sub/b.bin")).unwrap(), b);
            assert_eq!(corpus.list().len(), 2);
            assert_eq!(corpus.files().count(), 2);
            assert_eq!(fx.fetched_count(".list"), 1);
            assert_eq!(fx.fetched_count("a.bin"), 1);
            assert!(corpus.path().join(CACHED_LIST_NAME).is_file());

            // Second pull: list re-fetched, nothing else.
            fx.reset_log();
            let again = fx.pull(fx.options()).unwrap();
            assert_eq!(again.path(), corpus.path());
            assert_eq!(fx.fetched_count(".list"), 1);
            assert_eq!(fx.fetched_count("a.bin"), 0);
            assert_eq!(fx.fetched_count("b.bin"), 0);

            // Corrupt a cached file: the next pull repairs exactly that one.
            std::fs::write(corpus.file_path("a.bin"), b"tampered").unwrap();
            fx.reset_log();
            fx.pull(fx.options()).unwrap();
            assert_eq!(fx.fetched_count("a.bin"), 1);
            assert_eq!(fx.fetched_count("b.bin"), 0);
            assert_eq!(std::fs::read(corpus.file_path("a.bin")).unwrap(), a);
            fx.cleanup();
        }

        #[test]
        fn pull_rejects_checksum_mismatch_and_places_nothing() {
            let fx = Fixture::new("mismatch");
            fx.put_object("a.bin", b"actual bytes");
            let mut list = list_with(&[("a.bin", b"actual bytes", false)], None);
            list.files.get_mut("a.bin").unwrap().sha256 = sha256::sha256_hex(b"other");
            fx.put_list(&list);

            let err = fx.pull(fx.options()).unwrap_err();
            assert!(
                matches!(err, Error::ChecksumMismatch { ref path, .. } if path == "a.bin"),
                "{err}"
            );
            let dir = cache_dir_for(&fx.cache, BASE, PREFIX);
            assert!(!dir.join("a.bin").exists(), "mismatched file must not land");
            assert!(
                !dir.join(CACHED_LIST_NAME).exists(),
                "failed pull must not record the list"
            );
            // No temp droppings either.
            let temps = std::fs::read_dir(&dir)
                .unwrap()
                .flatten()
                .filter(|e| e.file_name().to_string_lossy().starts_with(".tmp-"))
                .count();
            assert_eq!(temps, 0);
            fx.cleanup();
        }

        #[test]
        fn pull_uses_bundle_when_enough_files_are_missing() {
            let fx = Fixture::new("bundle");
            let members: Vec<(String, Vec<u8>)> = (0..10)
                .map(|i| {
                    (
                        format!("seed{i}.bin"),
                        format!("seed number {i} payload").into_bytes(),
                    )
                })
                .collect();
            let tar = ustar(
                &members
                    .iter()
                    .map(|(n, d)| (n.as_str(), d.as_slice()))
                    .collect::<Vec<_>>(),
            );
            let bundle_key = format!("{}.tar", PREFIX.trim_end_matches('/'));
            fx.put_raw(&bundle_key, &tar);
            let delta = b"delta added after the bundle".as_slice();
            fx.put_object("delta.bin", delta);
            // Bundled members are deliberately NOT uploaded as individual
            // objects, so any attempt to fetch them singly fails loudly.
            let mut files: Vec<(&str, &[u8], bool)> = members
                .iter()
                .map(|(n, d)| (n.as_str(), d.as_slice(), true))
                .collect();
            files.push(("delta.bin", delta, false));
            let list = list_with(
                &files,
                Some(BundleInfo {
                    key: bundle_key.clone(),
                    size: tar.len() as u64,
                    sha256: sha256::sha256_hex(&tar),
                    file_count: members.len() as u64,
                    uncompressed_size: members.iter().map(|(_, d)| d.len() as u64).sum(),
                }),
            );
            fx.put_list(&list);

            let corpus = fx.pull(fx.options()).unwrap();
            for (n, d) in &members {
                assert_eq!(&std::fs::read(corpus.file_path(n)).unwrap(), d, "{n}");
            }
            assert_eq!(std::fs::read(corpus.file_path("delta.bin")).unwrap(), delta);
            assert_eq!(fx.fetched_count(".tar"), 1, "bundle fetched once");
            assert_eq!(fx.fetched_count("delta.bin"), 1, "delta fetched singly");
            assert_eq!(
                fx.fetched_count("seed3.bin"),
                0,
                "bundled file not fetched singly"
            );

            // Warm cache with one bundled file missing: 1/10 < 40% → single
            // fetch would be attempted, which the fixture cannot serve...
            std::fs::remove_file(corpus.file_path("seed3.bin")).unwrap();
            fx.reset_log();
            let err = fx.pull(fx.options()).unwrap_err();
            assert!(matches!(err, Error::DownloadFailed { .. }), "{err}");
            assert_eq!(fx.fetched_count(".tar"), 0);
            // ...unless ForceBundle is requested.
            fx.reset_log();
            fx.pull(fx.options().mode(PullMode::ForceBundle)).unwrap();
            assert_eq!(fx.fetched_count(".tar"), 1);
            assert!(corpus.file_path("seed3.bin").is_file());

            // NoBundle on a cold cache must not touch the bundle at all.
            let _ = std::fs::remove_dir_all(&fx.cache);
            fx.reset_log();
            let err = fx.pull(fx.options().mode(PullMode::NoBundle)).unwrap_err();
            assert!(matches!(err, Error::DownloadFailed { .. }), "{err}");
            assert_eq!(fx.fetched_count(".tar"), 0);
            fx.cleanup();
        }

        #[test]
        fn pull_rejects_bundle_with_wrong_checksum() {
            let fx = Fixture::new("bundle-bad");
            let tar = ustar(&[("x.bin", b"x")]);
            let key = format!("{}.tar", PREFIX.trim_end_matches('/'));
            fx.put_raw(&key, &tar);
            let list = list_with(
                &[("x.bin", b"x", true)],
                Some(BundleInfo {
                    key: key.clone(),
                    size: tar.len() as u64,
                    sha256: sha256::sha256_hex(b"not the tar"),
                    file_count: 1,
                    uncompressed_size: 1,
                }),
            );
            fx.put_list(&list);
            let err = fx.pull(fx.options()).unwrap_err();
            assert!(
                matches!(err, Error::ChecksumMismatch { ref path, .. } if *path == key),
                "{err}"
            );
            fx.cleanup();
        }

        #[test]
        fn pull_prunes_unlisted_files_and_keeps_own_markers() {
            let fx = Fixture::new("prune");
            fx.put_object("keep.bin", b"keep");
            fx.put_list(&list_with(&[("keep.bin", b"keep", false)], None));
            let corpus = fx.pull(fx.options()).unwrap();
            let stale = corpus.path().join("old").join("gone.bin");
            std::fs::create_dir_all(stale.parent().unwrap()).unwrap();
            std::fs::write(&stale, b"stale").unwrap();

            fx.pull(fx.options()).unwrap();
            assert!(!stale.exists(), "unlisted file pruned");
            assert!(!stale.parent().unwrap().exists(), "emptied dir removed");
            assert!(corpus.path().join(CACHED_LIST_NAME).is_file());
            assert!(corpus.path().join("keep.bin").is_file());

            std::fs::create_dir_all(stale.parent().unwrap()).unwrap();
            std::fs::write(&stale, b"stale").unwrap();
            fx.pull(fx.options().prune(false)).unwrap();
            assert!(stale.exists(), "prune(false) leaves extras alone");
            fx.cleanup();
        }

        #[test]
        fn offline_mode_and_cached_list_fallback() {
            let fx = Fixture::new("offline");
            // Nothing cached yet: offline is an error, not a silent empty corpus.
            let err = fx.pull(fx.options().mode(PullMode::Offline)).unwrap_err();
            assert!(matches!(err, Error::NetworkUnavailable { .. }), "{err}");

            fx.put_object("a.bin", b"a");
            fx.put_list(&list_with(&[("a.bin", b"a", false)], None));
            fx.pull(fx.options()).unwrap();

            // Offline with a complete cache succeeds without any fetch.
            fx.reset_log();
            let c = fx.pull(fx.options().mode(PullMode::Offline)).unwrap();
            assert_eq!(fx.fetched_total(), 0);
            assert_eq!(std::fs::read(c.file_path("a.bin")).unwrap(), b"a");

            // Offline with a missing file fails loudly.
            std::fs::remove_file(c.file_path("a.bin")).unwrap();
            let err = fx.pull(fx.options().mode(PullMode::Offline)).unwrap_err();
            assert!(matches!(err, Error::PathNotFound { .. }), "{err}");

            // Network gone (remote wiped) but a cached list exists: Auto falls
            // back to the cached list and repairs from... nothing, so it fails
            // on the missing file; with the file present it succeeds.
            std::fs::remove_dir_all(&fx.remote).unwrap();
            let err = fx.pull(fx.options()).unwrap_err();
            assert!(matches!(err, Error::DownloadFailed { .. }), "{err}");
            std::fs::write(c.file_path("a.bin"), b"a").unwrap();
            let c2 = fx.pull(fx.options()).unwrap();
            assert_eq!(c2.list().len(), 1);
            fx.cleanup();
        }

        #[test]
        fn list_index_from_dir_hashes_files_and_roundtrips() {
            let fx = Fixture::new("from-dir");
            let d = fx.root.join("local");
            std::fs::create_dir_all(d.join("nested")).unwrap();
            std::fs::write(d.join("one.bin"), b"one").unwrap();
            std::fs::write(d.join("nested").join("two.bin"), b"two two").unwrap();
            std::fs::write(d.join(".hidden"), b"skip").unwrap();

            let list = ListIndex::from_dir(&d, "fuzz/demo/seeds").unwrap();
            assert_eq!(list.prefix, "fuzz/demo/seeds/");
            assert_eq!(list.version, LIST_VERSION);
            assert_eq!(list.len(), 2);
            assert_eq!(list.total_size(), 3 + 7);
            assert_eq!(list.files["one.bin"], entry(b"one", false));
            assert_eq!(list.files["nested/two.bin"], entry(b"two two", false));
            assert!(list.bundle.is_none());

            let back = ListIndex::parse(&list.to_json()).unwrap();
            assert_eq!(back, list);

            // A list built from a dir can be served and pulled back verbatim.
            fx.put_object("one.bin", b"one");
            fx.put_object("nested/two.bin", b"two two");
            fx.put_list(&list);
            let c = fx.pull(fx.options()).unwrap();
            assert_eq!(
                std::fs::read(c.file_path("nested/two.bin")).unwrap(),
                b"two two"
            );
            fx.cleanup();
        }

        #[test]
        fn parallel_fetch_places_every_file_and_fails_fast_on_mismatch() {
            let fx = Fixture::new("parallel");
            let objects: Vec<(String, Vec<u8>)> = (0..60)
                .map(|i| {
                    (
                        format!("d{}/obj{i}.bin", i % 4),
                        format!("object {i} payload {}", "x".repeat(i)).into_bytes(),
                    )
                })
                .collect();
            for (rel, bytes) in &objects {
                fx.put_object(rel, bytes);
            }
            let files: Vec<(&str, &[u8], bool)> = objects
                .iter()
                .map(|(r, b)| (r.as_str(), b.as_slice(), false))
                .collect();
            fx.put_list(&list_with(&files, None));

            let corpus = fx.pull(fx.options().parallelism(8)).unwrap();
            for (rel, bytes) in &objects {
                assert_eq!(
                    &std::fs::read(corpus.file_path(rel)).unwrap(),
                    bytes,
                    "{rel}"
                );
            }
            assert_eq!(
                fx.fetched_total(),
                1 + objects.len(),
                "every object fetched once"
            );
            let temps = std::fs::read_dir(corpus.path())
                .unwrap()
                .flatten()
                .filter(|e| e.file_name().to_string_lossy().starts_with(".tmp-"))
                .count();
            assert_eq!(temps, 0, "no temp droppings after a parallel pull");

            // Sequential (parallelism 1) and parallel produce identical trees.
            let _ = std::fs::remove_dir_all(&fx.cache);
            let seq = fx.pull(fx.options().parallelism(1)).unwrap();
            assert_eq!(seq.list().files, corpus.list().files);
            for (rel, bytes) in &objects {
                assert_eq!(&std::fs::read(seq.file_path(rel)).unwrap(), bytes, "{rel}");
            }

            // One bad checksum among many: the pull fails with that file's
            // mismatch, and that file is never placed.
            let _ = std::fs::remove_dir_all(&fx.cache);
            let mut list = list_with(&files, None);
            list.files.get_mut("d2/obj42.bin").unwrap().sha256 = sha256::sha256_hex(b"wrong");
            fx.put_list(&list);
            let err = fx.pull(fx.options().parallelism(8)).unwrap_err();
            assert!(
                matches!(err, Error::ChecksumMismatch { ref path, .. } if path == "d2/obj42.bin"),
                "{err}"
            );
            let dir = cache_dir_for(&fx.cache, BASE, PREFIX);
            assert!(!join_rel(&dir, "d2/obj42.bin").exists());
            assert!(
                !dir.join(CACHED_LIST_NAME).exists(),
                "failed pull must not record the list"
            );
            let temps = std::fs::read_dir(&dir)
                .unwrap()
                .flatten()
                .filter(|e| e.file_name().to_string_lossy().starts_with(".tmp-"))
                .count();
            assert_eq!(temps, 0);
            fx.cleanup();
        }

        #[test]
        fn hierarchical_pull_recurses_into_children() {
            let fx = Fixture::new("tree");
            const ROOT: &str = "fuzz/tree/";
            // fuzz/tree.list: one own file + two children.
            let mut root = list_for(ROOT, &[("README", b"root readme", false)], None);
            root.children = vec!["alpha".to_string(), "beta".to_string()];
            fx.put_raw("fuzz/tree/README", b"root readme");
            fx.put_list_at(ROOT, &root);
            // fuzz/tree/alpha.list
            fx.put_raw("fuzz/tree/alpha/a1.bin", b"alpha one");
            fx.put_raw("fuzz/tree/alpha/sub/a2.bin", b"alpha two");
            fx.put_list_at(
                "fuzz/tree/alpha/",
                &list_for(
                    "fuzz/tree/alpha/",
                    &[
                        ("a1.bin", b"alpha one", false),
                        ("sub/a2.bin", b"alpha two", false),
                    ],
                    None,
                ),
            );
            // fuzz/tree/beta.list — itself a node with a grandchild.
            let mut beta = list_for("fuzz/tree/beta/", &[], None);
            beta.children = vec!["gamma".to_string()];
            fx.put_list_at("fuzz/tree/beta/", &beta);
            fx.put_raw("fuzz/tree/beta/gamma/g.bin", b"gamma");
            fx.put_list_at(
                "fuzz/tree/beta/gamma/",
                &list_for("fuzz/tree/beta/gamma/", &[("g.bin", b"gamma", false)], None),
            );

            let corpus = fx.pull_prefix(ROOT, fx.options()).unwrap();
            assert_eq!(
                std::fs::read(corpus.file_path("README")).unwrap(),
                b"root readme"
            );
            assert_eq!(
                std::fs::read(corpus.file_path("alpha/a1.bin")).unwrap(),
                b"alpha one"
            );
            assert_eq!(
                std::fs::read(corpus.file_path("alpha/sub/a2.bin")).unwrap(),
                b"alpha two"
            );
            assert_eq!(
                std::fs::read(corpus.file_path("beta/gamma/g.bin")).unwrap(),
                b"gamma"
            );
            // Merged view: every file keyed relative to the root prefix.
            let keys: Vec<&str> = corpus.files().map(|(k, _)| k).collect();
            assert_eq!(
                keys,
                [
                    "README",
                    "alpha/a1.bin",
                    "alpha/sub/a2.bin",
                    "beta/gamma/g.bin"
                ]
            );
            assert_eq!(corpus.list().children, ["alpha", "beta"]);
            assert_eq!(
                fx.fetched_count(".list"),
                4,
                "root + alpha + beta + gamma lists"
            );
            // Each node caches its own list, so it can be pulled directly too.
            assert!(corpus.path().join("alpha").join(CACHED_LIST_NAME).is_file());
            assert!(
                corpus
                    .path()
                    .join("beta")
                    .join("gamma")
                    .join(CACHED_LIST_NAME)
                    .is_file()
            );
            let alpha = fx.pull_prefix("fuzz/tree/alpha/", fx.options()).unwrap();
            assert_eq!(alpha.path(), corpus.path().join("alpha"));
            assert_eq!(alpha.list().len(), 2);

            // A second pull re-fetches only the four lists, and the root
            // prune must not reach into the children's directories.
            fx.reset_log();
            fx.pull_prefix(ROOT, fx.options()).unwrap();
            assert_eq!(fx.fetched_total(), 4);
            assert!(corpus.file_path("alpha/sub/a2.bin").is_file());

            // Offline works across the whole tree from the cached lists.
            fx.reset_log();
            let off = fx
                .pull_prefix(ROOT, fx.options().mode(PullMode::Offline))
                .unwrap();
            assert_eq!(fx.fetched_total(), 0);
            assert_eq!(off.list().len(), 4);

            // recursive(false): own files only, no child list fetched.
            fx.reset_log();
            let shallow = fx.pull_prefix(ROOT, fx.options().recursive(false)).unwrap();
            assert_eq!(shallow.list().len(), 1);
            assert_eq!(fx.fetched_count(".list"), 1);

            // A child whose .list is missing fails the pull loudly.
            std::fs::remove_file(join_rel(&fx.remote, "fuzz/tree/beta/gamma.list")).unwrap();
            std::fs::remove_dir_all(corpus.path().join("beta")).unwrap();
            let err = fx.pull_prefix(ROOT, fx.options()).unwrap_err();
            assert!(matches!(err, Error::NetworkUnavailable { .. }), "{err}");
            fx.cleanup();
        }
    }

    #[test]
    fn children_are_validated() {
        let mut list = ListIndex::empty("fuzz/").unwrap();
        assert_eq!(list.prefix, "fuzz/");
        assert!(list.is_empty());
        list.add_child("zentiff").unwrap();
        list.add_child("zentiff").unwrap();
        list.add_child("apng").unwrap();
        assert_eq!(list.children, ["apng", "zentiff"]);
        assert!(list.add_child("a/b").is_err());
        assert!(list.add_child("..").is_err());
        assert_eq!(
            list.children,
            ["apng", "zentiff"],
            "rejected child not kept"
        );

        let back = ListIndex::parse(&list.to_json()).unwrap();
        assert_eq!(back, list);

        let collide = r#"{"version":1,"prefix":"p/","generated_at":"","files":{"kid/x":{"size":1,"sha256":"a"}},"children":["kid"]}"#;
        assert!(matches!(
            ListIndex::parse(collide),
            Err(Error::ListParse(_))
        ));
        let nested =
            r#"{"version":1,"prefix":"p/","generated_at":"","files":{},"children":["a/b"]}"#;
        assert!(matches!(ListIndex::parse(nested), Err(Error::ListParse(_))));
        let dup =
            r#"{"version":1,"prefix":"p/","generated_at":"","files":{},"children":["a","a"]}"#;
        assert!(matches!(ListIndex::parse(dup), Err(Error::ListParse(_))));
        // Old lists without the field still parse.
        let old = r#"{"version":1,"prefix":"p/","generated_at":"","files":{}}"#;
        assert!(ListIndex::parse(old).unwrap().children.is_empty());
    }
}
